import path from 'node:path'
import PDFDocument from 'pdfkit'

import { formatDateTime } from '@/lib/election-report'

/**
 * The official election report, as a branded PDF.
 *
 * Laid out to read as a signed institutional document rather than a data dump:
 * a cover carrying the National Youth Parliament mark and the headline result,
 * then summary figures, a regional turnout chart, and the full per-constituency
 * declaration with each winner named.
 *
 * Colours are the logo's own, sampled from public/ypg.jpg.
 */

const BRAND = {
    green: '#187B28',
    greenDark: '#0F5C1D',
    greenLight: '#E7F3EA',
    gold: '#F9C50F',
    red: '#DC0B10',
    ink: '#1A1A1A',
    muted: '#55555F',
    hairline: '#E3E5E3',
    zebra: '#F7F8F7',
}

const PAGE = { margin: 48 }
const LOGO_PATH = path.join(process.cwd(), 'public', 'brand', 'emblem.png')

function contentWidth(doc) {
    return doc.page.width - PAGE.margin * 2
}

/** Draws the tricolour rule used throughout the interface. */
function tricolour(doc, x, y, width, height = 3) {
    const third = width / 3
    doc.rect(x, y, third, height).fill(BRAND.red)
    doc.rect(x + third, y, third, height).fill(BRAND.gold)
    doc.rect(x + third * 2, y, third, height).fill(BRAND.green)
}

function sectionHeading(doc, text) {
    ensureSpace(doc, 60)
    doc.moveDown(0.8)
    const y = doc.y
    doc.font('Helvetica-Bold').fontSize(13).fillColor(BRAND.ink).text(text, PAGE.margin, y)
    doc.moveTo(PAGE.margin, doc.y + 4)
        .lineTo(doc.page.width - PAGE.margin, doc.y + 4)
        .lineWidth(0.5)
        .strokeColor(BRAND.hairline)
        .stroke()
    doc.moveDown(0.7)
}

/** Starts a new page when the remaining space cannot hold `needed` points. */
function ensureSpace(doc, needed) {
    if (doc.y + needed > doc.page.height - PAGE.margin - 30) {
        doc.addPage()
    }
}

function drawCover(doc, report) {
    const width = contentWidth(doc)

    tricolour(doc, PAGE.margin, PAGE.margin, width, 5)

    let y = PAGE.margin + 40

    try {
        doc.image(LOGO_PATH, doc.page.width / 2 - 45, y, { width: 90 })
        y += 100
    } catch {
        // The report must still generate if the brand asset is missing.
        y += 10
    }

    doc.font('Helvetica-Bold')
        .fontSize(9)
        .fillColor(BRAND.green)
        .text('NATIONAL YOUTH PARLIAMENT OF GHANA', PAGE.margin, y, {
            width,
            align: 'center',
            characterSpacing: 1.6,
        })

    y = doc.y + 16

    doc.font('Helvetica-Bold')
        .fontSize(24)
        .fillColor(BRAND.ink)
        .text(report.meta.electionName, PAGE.margin, y, { width, align: 'center' })

    y = doc.y + 6

    doc.font('Helvetica')
        .fontSize(13)
        .fillColor(BRAND.muted)
        .text('Official Election Report', PAGE.margin, y, { width, align: 'center' })

    y = doc.y + 26

    // Headline result panel
    const { summary } = report
    const panelHeight = 88
    doc.roundedRect(PAGE.margin, y, width, panelHeight, 6)
        .fillAndStroke(BRAND.greenLight, BRAND.green)

    const cells = [
        ['Ballots cast', summary.totalBallots.toLocaleString('en-GB')],
        ['Turnout', `${summary.turnoutPct}%`],
        ['Constituencies declared', `${summary.declaredConstituencies} of ${summary.totalConstituencies}`],
    ]
    const cellWidth = width / cells.length

    cells.forEach(([label, value], i) => {
        const cx = PAGE.margin + cellWidth * i
        doc.font('Helvetica-Bold')
            .fontSize(20)
            .fillColor(BRAND.greenDark)
            .text(value, cx, y + 22, { width: cellWidth, align: 'center' })
        doc.font('Helvetica')
            .fontSize(9)
            .fillColor(BRAND.muted)
            .text(label, cx, y + 52, { width: cellWidth, align: 'center' })
    })

    y += panelHeight + 30

    // Provenance block — who generated this, when, and over what period.
    const rows = [
        ['Election period', `${formatDateTime(report.meta.opensAt)}  to  ${formatDateTime(report.meta.closesAt)}`],
        ['First ballot', formatDateTime(report.meta.firstVoteAt)],
        ['Last ballot', formatDateTime(report.meta.lastVoteAt)],
        ['Report generated', formatDateTime(report.meta.generatedAt)],
        ['Generated by', report.meta.generatedBy ?? 'Not recorded'],
        ['Voting status at export', report.meta.isActive ? 'Open' : 'Closed'],
    ]

    doc.y = y
    rows.forEach(([label, value]) => {
        const rowY = doc.y
        doc.font('Helvetica').fontSize(9.5).fillColor(BRAND.muted).text(label, PAGE.margin, rowY, {
            width: 150,
        })
        doc.font('Helvetica-Bold')
            .fontSize(9.5)
            .fillColor(BRAND.ink)
            .text(value, PAGE.margin + 150, rowY, { width: width - 150 })
        doc.moveDown(0.45)
    })

    doc.moveDown(1)
    doc.font('Helvetica')
        .fontSize(8)
        .fillColor(BRAND.muted)
        .text(
            `Voter verification: ${report.meta.verificationMethod}`,
            PAGE.margin,
            doc.y,
            { width }
        )

    doc.moveDown(0.6)
    doc.font('Helvetica')
        .fontSize(8)
        .fillColor(BRAND.muted)
        .text(
            'Ballots are anonymous. No record in this system links a ballot to the voter who cast it, ' +
                'so this report can state how many people voted but never how any individual voted.',
            PAGE.margin,
            doc.y,
            { width }
        )
}

function drawSummary(doc, report) {
    const { summary } = report
    sectionHeading(doc, 'Summary statistics')

    const stats = [
        ['Registered voters', summary.totalRegistered],
        ['Verified voters', summary.totalVerified],
        ['Voters who cast a ballot', summary.totalVoted],
        ['Ballots recorded', summary.totalBallots],
        ['Turnout (of verified voters)', `${summary.turnoutPct}%`],
        ['Constituencies', summary.totalConstituencies],
        ['Constituencies contested', summary.contestedConstituencies],
        ['Candidates standing', summary.activeCandidates],
    ]

    const width = contentWidth(doc)
    const colWidth = width / 2
    const startY = doc.y

    stats.forEach(([label, value], i) => {
        const col = i % 2
        const row = Math.floor(i / 2)
        const x = PAGE.margin + col * colWidth
        const y = startY + row * 22

        doc.font('Helvetica').fontSize(9.5).fillColor(BRAND.muted).text(label, x, y, {
            width: colWidth - 70,
        })
        doc.font('Helvetica-Bold')
            .fontSize(9.5)
            .fillColor(BRAND.ink)
            .text(typeof value === 'number' ? value.toLocaleString('en-GB') : value, x + colWidth - 70, y, {
                width: 60,
                align: 'right',
            })
    })

    doc.y = startY + Math.ceil(stats.length / 2) * 22 + 8

    // Ballot reconciliation. Printed whether or not it balances — an official
    // report should show the check was performed, not only its failures.
    const rec = summary.ballotReconciliation
    ensureSpace(doc, 50)
    const boxY = doc.y
    doc.roundedRect(PAGE.margin, boxY, width, 34, 4).fillAndStroke(
        rec.balanced ? BRAND.greenLight : '#FDECEC',
        rec.balanced ? BRAND.green : BRAND.red
    )
    doc.font('Helvetica-Bold')
        .fontSize(9)
        .fillColor(rec.balanced ? BRAND.greenDark : BRAND.red)
        .text(
            rec.balanced
                ? 'Ballot reconciliation: BALANCED'
                : `Ballot reconciliation: DISCREPANCY OF ${Math.abs(rec.discrepancy)}`,
            PAGE.margin + 12,
            boxY + 8
        )
    doc.font('Helvetica')
        .fontSize(8.5)
        .fillColor(BRAND.muted)
        .text(
            `${rec.votersMarkedVoted.toLocaleString('en-GB')} voters marked as having voted; ` +
                `${rec.ballotsRecorded.toLocaleString('en-GB')} ballots recorded.`,
            PAGE.margin + 12,
            boxY + 20
        )
    doc.y = boxY + 44
}

function drawRegionalChart(doc, report) {
    if (report.regions.length === 0) return

    sectionHeading(doc, 'Turnout by region')

    const width = contentWidth(doc)
    const barHeight = 14
    const gap = 9
    const labelWidth = 130
    const valueWidth = 74
    const trackWidth = width - labelWidth - valueWidth

    const maxPct = Math.max(10, ...report.regions.map((r) => r.turnoutPct))

    for (const region of report.regions) {
        ensureSpace(doc, barHeight + gap + 10)
        const y = doc.y

        doc.font('Helvetica')
            .fontSize(9)
            .fillColor(BRAND.ink)
            .text(region.region, PAGE.margin, y + 2, {
                width: labelWidth - 8,
                ellipsis: true,
                lineBreak: false,
            })

        const trackX = PAGE.margin + labelWidth
        doc.roundedRect(trackX, y, trackWidth, barHeight, 3).fill(BRAND.zebra)

        const fillWidth = Math.max(1, (region.turnoutPct / maxPct) * trackWidth)
        doc.roundedRect(trackX, y, fillWidth, barHeight, 3).fill(BRAND.green)

        doc.font('Helvetica-Bold')
            .fontSize(8.5)
            .fillColor(BRAND.ink)
            .text(
                `${region.turnoutPct}%  (${region.ballots.toLocaleString('en-GB')})`,
                trackX + trackWidth + 8,
                y + 3,
                { width: valueWidth - 8, lineBreak: false }
            )

        doc.y = y + barHeight + gap
    }

    doc.moveDown(0.4)
    doc.font('Helvetica')
        .fontSize(7.5)
        .fillColor(BRAND.muted)
        .text('Bars show turnout as a percentage of registered voters in each region.', PAGE.margin, doc.y, {
            width,
        })
}

function drawRegionalTable(doc, report) {
    if (report.regions.length === 0) return

    sectionHeading(doc, 'Regional breakdown')

    const columns = [
        { header: 'Region', width: 150, align: 'left', get: (r) => r.region },
        { header: 'Consts.', width: 55, align: 'right', get: (r) => r.constituencies },
        { header: 'Registered', width: 75, align: 'right', get: (r) => r.registered },
        { header: 'Voted', width: 65, align: 'right', get: (r) => r.voted },
        { header: 'Ballots', width: 65, align: 'right', get: (r) => r.ballots },
        { header: 'Turnout', width: 65, align: 'right', get: (r) => `${r.turnoutPct}%` },
    ]

    drawTable(doc, columns, report.regions)
}

function drawTable(doc, columns, rows) {
    const rowHeight = 18
    const totalWidth = columns.reduce((sum, c) => sum + c.width, 0)

    const header = () => {
        const y = doc.y
        doc.rect(PAGE.margin, y, totalWidth, rowHeight).fill(BRAND.green)
        let x = PAGE.margin
        for (const col of columns) {
            doc.font('Helvetica-Bold')
                .fontSize(8)
                .fillColor('#FFFFFF')
                .text(col.header, x + 6, y + 5.5, {
                    width: col.width - 12,
                    align: col.align,
                    lineBreak: false,
                })
            x += col.width
        }
        doc.y = y + rowHeight
    }

    ensureSpace(doc, rowHeight * 3)
    header()

    rows.forEach((row, i) => {
        if (doc.y + rowHeight > doc.page.height - PAGE.margin - 30) {
            doc.addPage()
            header()
        }
        const y = doc.y
        if (i % 2 === 1) {
            doc.rect(PAGE.margin, y, totalWidth, rowHeight).fill(BRAND.zebra)
        }
        let x = PAGE.margin
        for (const col of columns) {
            const raw = col.get(row)
            const text = typeof raw === 'number' ? raw.toLocaleString('en-GB') : String(raw ?? '—')
            doc.font(col.bold ? 'Helvetica-Bold' : 'Helvetica')
                .fontSize(8.5)
                .fillColor(BRAND.ink)
                .text(text, x + 6, y + 5, {
                    width: col.width - 12,
                    align: col.align,
                    ellipsis: true,
                    lineBreak: false,
                })
            x += col.width
        }
        doc.y = y + rowHeight
    })

    doc.moveDown(0.5)
}

function drawConstituencyResults(doc, report) {
    doc.addPage()
    sectionHeading(doc, 'Constituency results')

    doc.font('Helvetica')
        .fontSize(8.5)
        .fillColor(BRAND.muted)
        .text(
            'Every candidate who stood is listed, including those who received no votes. ' +
                'Where two or more candidates are tied on the highest tally, all are shown as tied.',
            PAGE.margin,
            doc.y,
            { width: contentWidth(doc) }
        )
    doc.moveDown(0.8)

    const width = contentWidth(doc)

    for (const constituency of report.constituencies) {
        ensureSpace(doc, 90)

        const headerY = doc.y
        doc.rect(PAGE.margin, headerY, width, 24).fill(BRAND.zebra)
        doc.font('Helvetica-Bold')
            .fontSize(10)
            .fillColor(BRAND.ink)
            .text(constituency.name, PAGE.margin + 8, headerY + 7, {
                width: width - 200,
                ellipsis: true,
                lineBreak: false,
            })
        doc.font('Helvetica')
            .fontSize(8)
            .fillColor(BRAND.muted)
            .text(
                `${constituency.region ?? '—'}  ·  ${constituency.totalVotes.toLocaleString('en-GB')} ballots  ·  ${constituency.turnoutPct}% turnout`,
                PAGE.margin + width - 200,
                headerY + 8,
                { width: 192, align: 'right', lineBreak: false }
            )
        doc.y = headerY + 30

        if (constituency.candidates.length === 0) {
            doc.font('Helvetica-Oblique')
                .fontSize(8.5)
                .fillColor(BRAND.muted)
                .text('No candidates stood in this constituency.', PAGE.margin + 8, doc.y)
            doc.moveDown(1)
            continue
        }

        const winnerIds = new Set(constituency.winners.map((w) => w.id))
        const tied = constituency.winners.length > 1

        for (const candidate of constituency.candidates) {
            ensureSpace(doc, 26)
            const y = doc.y
            const isWinner = winnerIds.has(candidate.id)

            doc.font(isWinner ? 'Helvetica-Bold' : 'Helvetica')
                .fontSize(9)
                .fillColor(BRAND.ink)
                .text(candidate.name, PAGE.margin + 8, y, {
                    width: width - 260,
                    ellipsis: true,
                    lineBreak: false,
                })

            if (isWinner) {
                doc.font('Helvetica-Bold')
                    .fontSize(7)
                    .fillColor(BRAND.greenDark)
                    .text(tied ? 'TIED' : 'ELECTED', PAGE.margin + width - 252, y + 1, {
                        width: 44,
                        lineBreak: false,
                    })
            }

            // Share bar
            const barX = PAGE.margin + width - 200
            const barWidth = 110
            doc.roundedRect(barX, y + 1, barWidth, 8, 2).fill('#EDEEED')
            if (candidate.sharePct > 0) {
                doc.roundedRect(
                    barX,
                    y + 1,
                    Math.max(1.5, (candidate.sharePct / 100) * barWidth),
                    8,
                    2
                ).fill(isWinner ? BRAND.green : '#A9AFAA')
            }

            doc.font('Helvetica')
                .fontSize(8.5)
                .fillColor(BRAND.ink)
                .text(
                    `${candidate.votes.toLocaleString('en-GB')}  ·  ${candidate.sharePct}%`,
                    barX + barWidth + 8,
                    y,
                    { width: 82, align: 'right', lineBreak: false }
                )

            doc.y = y + 16
        }

        doc.moveDown(0.7)
    }
}

/** Page numbers and a running footer, applied once the body is laid out. */
function paginate(doc, report) {
    const range = doc.bufferedPageRange()
    for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i)

        // The footer sits below the bottom margin, and pdfkit responds to text
        // written past that margin by starting a new page — which produced a
        // blank page per footer and left the real pages unfooted. Dropping the
        // margin for the duration of the write suppresses that pagination.
        const originalBottomMargin = doc.page.margins.bottom
        doc.page.margins.bottom = 0

        const y = doc.page.height - PAGE.margin + 8
        const width = contentWidth(doc)

        doc.moveTo(PAGE.margin, y - 8)
            .lineTo(doc.page.width - PAGE.margin, y - 8)
            .lineWidth(0.5)
            .strokeColor(BRAND.hairline)
            .stroke()

        doc.font('Helvetica')
            .fontSize(7.5)
            .fillColor(BRAND.muted)
            .text(`${report.meta.electionName} — Official Election Report`, PAGE.margin, y, {
                width: width / 2,
                lineBreak: false,
            })

        doc.font('Helvetica')
            .fontSize(7.5)
            .fillColor(BRAND.muted)
            .text(`Page ${i - range.start + 1} of ${range.count}`, PAGE.margin + width / 2, y, {
                width: width / 2,
                align: 'right',
                lineBreak: false,
            })

        doc.page.margins.bottom = originalBottomMargin
    }
}

/**
 * @returns {Promise<Buffer>} the rendered PDF
 */
export function renderReportPdf(report) {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: 'A4',
            margin: PAGE.margin,
            // Required so paginate() can revisit pages to stamp page numbers.
            bufferPages: true,
            info: {
                Title: `${report.meta.electionName} — Official Election Report`,
                Author: 'National Youth Parliament of Ghana',
                Subject: 'Election results and turnout',
                Creator: 'National Youth Parliament Voting Platform',
                CreationDate: new Date(report.meta.generatedAt),
            },
        })

        const chunks = []
        doc.on('data', (chunk) => chunks.push(chunk))
        doc.on('end', () => resolve(Buffer.concat(chunks)))
        doc.on('error', reject)

        try {
            drawCover(doc, report)
            doc.addPage()
            drawSummary(doc, report)
            drawRegionalChart(doc, report)
            drawRegionalTable(doc, report)
            drawConstituencyResults(doc, report)
            paginate(doc, report)
            doc.end()
        } catch (error) {
            reject(error)
        }
    })
}
