import { STYLE } from '@/lib/export/xlsx'
import { formatDateTime } from '@/lib/election-report'

/**
 * The report's tabular shape, defined once.
 *
 * The Excel workbook and the CSV export are generated from the same row
 * definitions here, so the two can never disagree about what a column means or
 * which figures a report contains.
 */

const num = (value) => ({ value, style: STYLE.NUMBER })
const pct = (value) => ({ value, style: STYLE.PERCENT })
const head = (value) => ({ value, style: STYLE.HEADER })

export function summaryRows(report) {
    const { meta, summary } = report
    const rec = summary.ballotReconciliation

    return [
        [{ value: meta.electionName, style: STYLE.TITLE }],
        [{ value: 'Official Election Report', style: STYLE.MUTED }],
        [],
        [head('Field'), head('Value')],
        ['Election', meta.electionName],
        ['Description', meta.description ?? '—'],
        ['Voting opens', formatDateTime(meta.opensAt)],
        ['Voting closes', formatDateTime(meta.closesAt)],
        ['Voting status at export', meta.isActive ? 'Open' : 'Closed'],
        ['First ballot cast', formatDateTime(meta.firstVoteAt)],
        ['Last ballot cast', formatDateTime(meta.lastVoteAt)],
        ['Report generated', formatDateTime(meta.generatedAt)],
        ['Generated by', meta.generatedBy ?? 'Not recorded'],
        ['Voter verification', meta.verificationMethod],
        [],
        [head('Statistic'), head('Value')],
        ['Total registered voters', num(summary.totalRegistered)],
        ['Total verified voters', num(summary.totalVerified)],
        ['Voters who cast a ballot', num(summary.totalVoted)],
        ['Total ballots recorded', num(summary.totalBallots)],
        ['Turnout %', pct(summary.turnoutPct)],
        ['Total constituencies', num(summary.totalConstituencies)],
        ['Constituencies contested', num(summary.contestedConstituencies)],
        // Relabelled: this counts seats that produced a member, which after the
        // eligibility rule is no longer the same as "ballots were cast here".
        ['Seats declared (elected)', num(summary.declaredConstituencies)],
        ['Constituencies requiring a re-election', num(summary.reElectionConstituencies)],
        ['Minimum votes to be elected', num(summary.minVotesToBeElected)],
        ['Total candidates', num(summary.totalCandidates)],
        ['Candidates standing', num(summary.activeCandidates)],
        [],
        [head('Ballot reconciliation'), head('Value')],
        ['Voters marked as voted', num(rec.votersMarkedVoted)],
        ['Ballots recorded', num(rec.ballotsRecorded)],
        ['Discrepancy', num(rec.discrepancy)],
        ['Status', rec.balanced ? 'Balanced' : 'DISCREPANCY — investigate'],
    ]
}

const RESULT_HEADERS = [
    'Constituency',
    'Region',
    'Code',
    'Candidate',
    'Votes',
    'Share %',
    'Outcome',
    'Constituency ballots',
    'Registered voters',
    'Turnout %',
]

export function resultRows(report, { styled = true } = {}) {
    const h = styled ? head : (v) => v
    const n = styled ? num : (v) => v
    const p = styled ? pct : (v) => v

    const rows = [RESULT_HEADERS.map(h)]

    for (const c of report.constituencies) {
        const winnerIds = new Set(c.winners.map((w) => w.id))
        const tied = c.winners.length > 1

        // A constituency where nobody stood now reaches this sheet (it used to
        // be absent entirely) and has no candidate rows to carry it, so it gets
        // one row of its own. Otherwise the export would still be missing 132
        // of the 276 seats.
        if (c.candidates.length === 0) {
            rows.push([
                c.name,
                c.region ?? '',
                c.code ?? '',
                '',
                n(0),
                p(0),
                c.reason ?? 'Re-election',
                n(0),
                n(c.registered),
                p(c.turnoutPct),
            ])
            continue
        }

        for (const candidate of c.candidates) {
            rows.push([
                c.name,
                c.region ?? '',
                c.code ?? '',
                candidate.name,
                // Historical tallies, exported exactly as counted. The
                // eligibility rule changes the Outcome column and nothing else.
                n(candidate.votes),
                p(candidate.sharePct),
                winnerIds.has(candidate.id)
                    ? tied
                        ? 'Tied'
                        : 'Elected'
                    : c.reElection
                      ? 'Re-election'
                      : '',
                n(c.totalVotes),
                n(c.registered),
                p(c.turnoutPct),
            ])
        }
    }

    return rows
}

const TURNOUT_HEADERS = [
    'Constituency',
    'Region',
    'Code',
    'Registered',
    'Verified',
    'Voted',
    'Ballots',
    'Turnout %',
    'Candidates',
]

export function constituencyTurnoutRows(report, { styled = true } = {}) {
    const h = styled ? head : (v) => v
    const n = styled ? num : (v) => v
    const p = styled ? pct : (v) => v

    return [
        TURNOUT_HEADERS.map(h),
        ...report.constituencies.map((c) => [
            c.name,
            c.region ?? '',
            c.code ?? '',
            n(c.registered),
            n(c.verified),
            n(c.totalVotes),
            n(c.totalVotes),
            p(c.turnoutPct),
            n(c.candidates.length),
        ]),
    ]
}

export function regionRows(report, { styled = true } = {}) {
    const h = styled ? head : (v) => v
    const n = styled ? num : (v) => v
    const p = styled ? pct : (v) => v

    return [
        ['Region', 'Constituencies', 'Registered', 'Voted', 'Ballots', 'Turnout %'].map(h),
        ...report.regions.map((r) => [
            r.region,
            n(r.constituencies),
            n(r.registered),
            n(r.voted),
            n(r.ballots),
            p(r.turnoutPct),
        ]),
    ]
}

export function winnerRows(report, { styled = true } = {}) {
    const h = styled ? head : (v) => v
    const n = styled ? num : (v) => v
    const p = styled ? pct : (v) => v

    const rows = [
        ['Constituency', 'Region', 'Elected candidate', 'Votes', 'Share %', 'Outcome'].map(h),
    ]

    for (const c of report.constituencies) {
        // No elected member. The candidate who led is still named, with the
        // tally they actually received, because withdrawing the seat is not the
        // same as erasing the count — an auditor reading this sheet has to be
        // able to see both what happened and why it produced nobody.
        if (c.winners.length === 0) {
            const leader = c.leadingCandidates?.[0]
            rows.push([
                c.name,
                c.region ?? '',
                leader ? `${leader.name} (led, not elected)` : 'No candidate stood',
                n(leader?.votes ?? 0),
                p(0),
                c.reason ?? 'Re-election',
            ])
            continue
        }
        const tied = c.winners.length > 1
        for (const w of c.winners) {
            rows.push([
                c.name,
                c.region ?? '',
                w.name,
                n(w.votes),
                p(w.sharePct),
                tied ? 'Tied' : 'Elected',
            ])
        }
    }

    return rows
}

/** The workbook: one sheet per view an election officer needs. */
export function buildWorkbookSheets(report) {
    return [
        {
            name: 'Summary',
            rows: summaryRows(report),
            columnWidths: [34, 46],
        },
        {
            name: 'Winners',
            rows: winnerRows(report),
            columnWidths: [26, 20, 26, 10, 10, 12],
            freezeRows: 1,
            autoFilter: 'A1:F1',
        },
        {
            name: 'Full results',
            rows: resultRows(report),
            columnWidths: [26, 20, 8, 26, 10, 10, 11, 19, 17, 11],
            freezeRows: 1,
            autoFilter: 'A1:J1',
        },
        {
            name: 'Constituency turnout',
            rows: constituencyTurnoutRows(report),
            columnWidths: [26, 20, 8, 12, 11, 10, 10, 11, 12],
            freezeRows: 1,
            autoFilter: 'A1:I1',
        },
        {
            name: 'Regions',
            rows: regionRows(report),
            columnWidths: [24, 16, 13, 11, 11, 12],
            freezeRows: 1,
        },
    ]
}

/**
 * CSV is a single flat table, so it carries the full per-candidate results
 * with a short provenance preamble. The preamble is comment-free plain rows so
 * that a spreadsheet still opens it cleanly.
 */
export function buildCsvRows(report) {
    const { meta, summary } = report
    return [
        [meta.electionName, 'Official Election Report'],
        ['Election period', `${formatDateTime(meta.opensAt)} to ${formatDateTime(meta.closesAt)}`],
        ['Generated', formatDateTime(meta.generatedAt)],
        ['Generated by', meta.generatedBy ?? 'Not recorded'],
        ['Registered voters', summary.totalRegistered],
        ['Verified voters', summary.totalVerified],
        ['Ballots cast', summary.totalBallots],
        ['Turnout %', summary.turnoutPct],
        [],
        ...resultRows(report, { styled: false }),
    ]
}
